version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17011996
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
    - app_network
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:dFGzDIFSz5aGVy8@db.erobcmncvrabujsfvtqr.supabase.co:5432/postgres"
    depends_on:
      postgres:
        condition: service_healthy        
    networks:
    - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge